/**
 * IMPORTANT: This module must NOT use node:fs at runtime.
 * Cloudflare Workers has no filesystem access.
 *
 * - Metadata functions (getAllPostMeta, getPostMeta, etc.) use the static
 *   posts-manifest.json generated by `scripts/generate-posts-manifest.mjs`
 *   at build time.
 * - getCompiledPost uses node:fs but is only ever called inside
 *   generateStaticParams / page-level server functions (build time only).
 */

import { compileMDX } from "next-mdx-remote/rsc";
import rehypeShiki from "@shikijs/rehype";
import rehypeSlug from "rehype-slug";
import remarkGfm from "remark-gfm";
import { mdxComponents } from "@/components/mdx";
import manifest from "./posts-manifest.json";

export type PostFrontmatter = {
  title: string;
  date: string;
  excerpt: string;
  tags: string[];
  featured: boolean;
  coverImage: string | null;
  draft: boolean;
};

export type PostMeta = PostFrontmatter & {
  slug: string;
  readingTime: number;
};

// Cast the static JSON manifest to typed PostMeta[]
const allPosts: PostMeta[] = manifest as PostMeta[];

export function getAllPostMeta(): PostMeta[] {
  return allPosts;
}

export function getPostMeta(slug: string): PostMeta | null {
  return allPosts.find((p) => p.slug === slug) ?? null;
}

export async function getCompiledPost(slug: string) {
  // node:fs is only available at build time (generateStaticParams).
  // Dynamic require keeps it out of the Cloudflare Worker bundle.
  const fs = await import("node:fs");
  const path = await import("node:path");
  const { default: readingTime } = await import("reading-time");

  const POSTS_DIR = path.join(process.cwd(), "content", "posts");
  const raw = fs.readFileSync(path.join(POSTS_DIR, `${slug}.mdx`), "utf-8");

  const { content, frontmatter } = await compileMDX<PostFrontmatter>({
    source: raw,
    components: mdxComponents,
    options: {
      parseFrontmatter: true,
      mdxOptions: {
        remarkPlugins: [remarkGfm],
        rehypePlugins: [
          rehypeSlug,
          [rehypeShiki, { theme: "github-dark-default" }],
        ],
      },
    },
  });

  const bodyText = raw.split("---").slice(2).join("---");
  const meta: PostMeta = {
    ...frontmatter,
    slug,
    readingTime: Math.ceil(readingTime(bodyText).minutes),
  };

  return { content, meta };
}

export function getAllTags(): string[] {
  const tags = new Set<string>();
  getAllPostMeta().forEach((p) => p.tags.forEach((t) => tags.add(t)));
  return Array.from(tags).sort();
}

export function getAdjacentPosts(slug: string): { prev: PostMeta | null; next: PostMeta | null } {
  const posts = getAllPostMeta();
  const i = posts.findIndex((p) => p.slug === slug);
  return {
    prev: i < posts.length - 1 ? posts[i + 1] : null,
    next: i > 0 ? posts[i - 1] : null,
  };
}

export function getRelatedPosts(slug: string, limit = 3): PostMeta[] {
  const posts = getAllPostMeta();
  const current = posts.find((p) => p.slug === slug);
  if (!current) return [];
  return posts
    .filter((p) => p.slug !== slug)
    .map((p) => ({ post: p, score: p.tags.filter((t) => current.tags.includes(t)).length }))
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((r) => r.post);
}
